name: sanitizer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        sanitizer: ["address", "thread"]

    env:
      CC: clang-14
      CXX: clang++-14

    steps:
    - uses: actions/checkout@v3

    - name: Install build tools
      run: >
        sudo apt-get update
        && sudo apt-get install -y clang-14 ninja-build

    - name: Install package manager
      run: >
        pipx install conan
        && conan profile detect

    - name: Install dependencies
      #
      # Download packages listed in our manifest. Generate toolchain file for
      # CMake so that we can use find_package(...) to find deps
      #
      run: >
        conan install .
        --build=missing
        -s build_type=Debug
        -s compiler.libcxx=libc++

    - name: Configure
      #
      # Configure CMake in the "build" subdirectory.
      #
      working-directory: build/Debug
      run: >
        cmake ../.. -GNinja
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_CXX_FLAGS="-fsanitize=${{ matrix.sanitizer }}"
        -DCMAKE_TOOLCHAIN_FILE=generators/conan_toolchain.cmake

    - name: Build
      #
      # Build all enabled programs with the current configuration.
      #
      working-directory: build/Debug
      run: cmake --build .

    - name: Test
      #
      # Run tests defined by CTest.
      #
      working-directory: build/Debug
      env:
        ASAN_OPTIONS: detect_leaks=1:color=always
        TSAN_OPTIONS: halt_on_error=1:second_deadlock_stack=1
      run: ctest --output-on-failure
