name: sanitizer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        sanitizer: ["address", "thread"]

    env:
      CC: clang-14
      CXX: clang++-14

    steps:
    - uses: actions/checkout@v3

    - name: Install build tools
      run: >
        sudo apt-get update
        && sudo apt-get install -y clang-14 ninja-build

    - name: Install package manager
      run: >
        pip3 install conan --upgrade
        && conan profile new default --detect
        && conan profile update settings.build_type=Debug default
        && conan profile update settings.compiler.libcxx=libc++ default

    - name: Install dependencies
      #
      # Download packages listed in our manifest. Generate toolchain file for
      # CMake so that we can use find_package(...) to find deps
      #
      run: >
        install -d build
        && cd build
        && conan install .. --build=missing

    - name: Configure
      #
      # Configure CMake in the "build" subdirectory.
      #
      working-directory: build
      run: >
        cmake .. -GNinja
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_CXX_FLAGS="-fsanitize=${{ matrix.sanitizer }}"
        -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake

    - name: Build
      #
      # Build all enabled programs with the current configuration.
      #
      working-directory: build
      run: cmake --build .

    - name: Test
      #
      # Execute tests defined by the CMake configuration. In our project this
      # is any executable target that has an associated add_test(NAME target).
      #
      # Example:
      #   add_executable(unit_test unit_test.cpp)
      #   add_test(UnitTestName unit_test)
      #
      working-directory: build
      env:
        ASAN_OPTIONS: detect_leaks=1:color=always:alloc_dealloc_mismatch=0
        TSAN_OPTIONS: halt_on_error=1:second_deadlock_stack=1
      run: ctest --output-on-failure
