#
# Workflow for C++ continuous integration (CI) with cmake and conan
# - Run on pull request and push to main branch
# - Install dependencies with conan
# - Use conan to call CMake to configure and build
# - Use CTest to run tests
#
name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      
      matrix:
        os: [windows-2022, macos-12, ubuntu-22.04]

    steps:
    - uses: actions/checkout@v3

    - name: Install package manager
      #
      # Install conan and autodetect the build profile. Defaults are:
      #
      # settings.build_type=Release
      #
      # - Windows Server 2022
      #   settings.compiler=Visual Studio
      #   settings.compiler.version=17
      #
      # - macOS 12.6
      #   settings.compiler=apple-clang
      #   settings.compiler.version=14
      #   settings.compiler.libcxx=libc++
      #
      # - Ubuntu 22.04
      #   settings.compiler=gcc
      #   settings.compiler.version=11
      #   settings.compiler.libcxx=libstdc++
      #
      run: >
        pipx install conan
        && conan profile detect

    - name: Install dependencies
      #
      # Download packages listed in our manifest. Generate toolchain file for
      # CMake so that we can use find_package(...) to find deps.
      #
      run: conan install . --build=missing
      
    - name: Build
      #
      # Configure with CMake and build all enabled apps.
      #
      run: conan build .

    - name: Test
      #
      # Execute tests defined by the CMake configuration.
      #
      working-directory: build/Release
      run: ctest --output-on-failure --config=Release
