#
# Workflow for C++ continuous integration (CI) with cmake and conan
# - Run on pull request and push to main branch
# - Install dependencies with conan
# - Use conan to call CMake to configure and build
# - Use CTest to run tests
#
name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      
      matrix:
        os: [windows-2022, macos-12, ubuntu-22.04]

    steps:
    - uses: actions/checkout@v3

    - name: Install package manager
      run: >
        pipx install ninja
        && pipx install conan
        && conan profile detect

    - name: Build
      run: >
        conan build . --build=missing
        -c tools.cmake.cmaketoolchain:generator=Ninja
 
    - name: Test
      #
      # Run tests defined by CTest.
      #
      working-directory: build/Release
      run: ctest --output-on-failure --config=Release
