name: tidy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      CC: clang-14
      CXX: clang++-14

    steps:
    - uses: actions/checkout@v3

    - name: Install build tools
      run: >
        sudo apt-get update
        && sudo apt-get install -y clang-14 ninja-build

    - name: Install package manager
      run: >
        pipx install conan
        && conan profile detect

    - name: Install dependencies
      #
      # Download packages listed in our manifest. Generate toolchain file for
      # CMake so that we can use find_package(...) to find deps
      #
      run: conan install . --build=missing --profile=tools/clang-jammy.profile

    - name: Configure
      #
      # Configure CMake in the "build" subdirectory.
      #
      working-directory: build/Release
      run: >
        cmake ../.. -GNinja
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_CXX_CLANG_TIDY=clang-tidy-14
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        -DCMAKE_TOOLCHAIN_FILE=generators/conan_toolchain.cmake
        -DBUILD_TESTING=OFF

    - name: Build
      #
      # Build all enabled programs with the current configuration.
      #
      working-directory: build/Release
      run: cmake --build .
